Objetivo 1
jesusmarzor/Proyecto-IV pull request #6
Opened 2021-09-24 09:47 UTC by jesusmarzor

2021-09-25 08:24 UTC, JJ requested changes
Sin un "user journey", es imposible entender en qué consisten las diferentes historias de usuario. Por favor trata de entender correctamente el concepto de producto mínimamente viable, que sería lo que se entregaría en cada hito; por tanto, un hito será siempre una descripción de ese producto mínimamente viable "Elección" no parece la descripción de un producto.

2021-09-25 08:24 UTC, JJ commented on README.md
> +<p>Leer la documentación adicional <a href="./docs/Objetivo-0/CONFIGURACION.md">aquí<a>
No estás usando markdown sino HTML. Pásate un día por clase y te doy una guía en un librito de markdown, hombre.

2021-09-25 13:56 UTC, jesusmarzor commented on README.md
> +<p>Leer la documentación adicional <a href="./docs/Objetivo-0/CONFIGURACION.md">aquí<a>
Me creía que también se aceptaba las etiquetas de HTML. Lo acabo de pasar todo a sintaxis Markdown. :laughing:

2021-09-26 07:33 UTC, JJ requested changes
Recordarás que en [este comentario](https://github.com/jesusmarzor/Proyecto-IV/pull/1#pullrequestreview-758114246) aprobé provisionalmente el objetivo. En este objetivo es dónde tenías que haber comentado claramente cuál es la lógica de negocio y/o valor añadido. Si crees que dentro del mismo tipo de problema puedes hacerlo, adelante. Si no, tendrás que cambiar el problema y la solución de forma que 
1. La mejor forma sea implementarlo en un servidor.
2. Tenga una lógica de negocio que vaya más allá de almacenar y recuperar.

2021-09-26 07:33 UTC, JJ commented on README.md
> +La aplicación hará una estadística semanal sobre cuanto tiempo tardas en cada tarea y la próxima vez que añadas esa tarea, te propondrá un tiempo mínimo para realizarla.
Realmente no me parece que la solución sea razonable. Una tarea como "Ir al Mercadona" puede tardar desde 20 minutos a una hora y media. "Ponerte a trabajar en el objetivo de IV" desde 10 minutos a 4 horas. Tendrás que buscar otro tipo de problema y solución, porque con este, salvo datos falsos y sin mucho sentido, no vamos a obtener nada. 
"Apuntar las tareas diarias" tiene cierto potencial, pero para que se convierta en una aplicación tienes que poner alguna lógica de negocio detrás, como clasificación automática de tareas, análisis de sentimiento en la descripción de la tarea. Por otro lado, tampoco parece que sea una aplicación que necesite un servidor. Por favor, pensad en aplicaciones que necesiten un servidor y cuya implementación más razonable y mínima haga uso de él.

2021-09-26 07:33 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +**Organizador** - El único usuario que estará presente en la aplicación ya que es una aplicación de desarrollo personal.
Por eso mismo es una aplicación que se ejecutaría más razonablemente en un ordenador o dispositivo personal. ¿Qué sentido tiene que despliegues a la nube algo que es una aplicación puramente personal?

2021-09-28 07:40 UTC, jesusmarzor commented on docs/Objetivo-1/ISSUES.md
> +**Organizador** - El único usuario que estará presente en la aplicación ya que es una aplicación de desarrollo personal.
He cambiado el problema y he realizado el objetivo-1 respecto al nuevo problema.

2021-09-28 14:37 UTC, jesusmarzor commented
Listo para revisión.

2021-09-28 15:20 UTC, JJ requested changes

2021-09-28 15:20 UTC, JJ commented on README.md
> +Con esta aplicación web, ¡ este problema debería resolverse !
Vas muy bien, y me encanta la presentación... A ver cómo lo solucionas.

2021-09-28 15:20 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +**Cliente** - Persona que pide cita en el calendario para acudir a la empresa.
... y falla. ¿Dónde está aquí la solución al problema?

2021-09-28 15:58 UTC, jesusmarzor commented on docs/Objetivo-1/ISSUES.md
> +**Cliente** - Persona que pide cita en el calendario para acudir a la empresa.
He añadido las HUs enumeradas al markdown para que se entienda mejor que piden los usuarios.

2021-09-28 18:46 UTC, jesusmarzor commented
Me he dado cuenta que no estaba implementado el Sistema de Control de Pago. Sin este sistema, el cliente no paga, con lo cual no hay ninguna solución al problema para la empresa. Ya he añadido un sistema de pago para el cliente ::smile:: .

2021-09-29 05:30 UTC, JJ approved these changes
Esencialmente, el objetivo está cumplido. Sin embargo, quedan unos flecos que te agradecería que revisaras antes del siguiente hito. El fleco más importante es que tienes que tener en cuenta que se va a ejecutar en la nube, por lo que las predicciones (o la lógica de negocio que fuera) podría tener en cuenta datos procedentes de diferentes negocios (de hecho, ese sería el valor que se aportaría por parte de esta aplicación)

2021-09-29 05:30 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +[[HU3](https://github.com/jesusmarzor/Proyecto-IV/issues/13)] &#8594; Como cliente, quiero pagar el coste del servicio a la hora de reservar la cita.
Esta historia es de UI. Está claro que la aplicación terminada tiene que incluirlo. No está tanto cómo contribuye a la lógica de negocio.

2021-09-29 05:30 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +[[HU4](https://github.com/jesusmarzor/Proyecto-IV/issues/5)] &#8594; Como cliente, quiero tener a mano una forma de contacto con la empresa(email,teléfono,formulario) por si tengo algún problema.
UI sólo. No es relevante a IV.

2021-09-29 05:30 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +[[HU5](https://github.com/jesusmarzor/Proyecto-IV/issues/7)] &#8594; Como trabajador, quiero consultar las citas para ir comprobando las citas de los clientes.
Toda HU tiene que mencionar el contexto (Dado que...) y el beneficio que el usuario obtiene de la misma. Si es simplemente una funcionalidad, es algo que hay que hacer sí o sí.

2021-09-29 05:30 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +[[HU7](https://github.com/jesusmarzor/Proyecto-IV/issues/9)] &#8594; Como gestor, quiero predecir qué cantidad de cada producto debo disponer semanalmente.
... dado que... El contexto es esencial para saber qué lógica de negocio se necesita probramar. Y entiendo que la lógica de negocio está aquí. El resto de las HU, casi en su totalidad, deben servir a esta. Por favor, también especifica un poco más. El "dado que" es esencial. ¿Qué datos necesita para hacer esa predicción?

2021-09-29 05:30 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +
Dado que... 
También cuando quiere predecirlo, claro. ¿Está relacionado con #9? Todas las HUs tienen que ser aspectos de la lógica de negocio, y tienen que servir para obtener algún beneficio. ¿Para qué quieres predecir los clientes? ¿Se contrata más o menos gente? ¿O sólo por los productos? Si es así, ¿no será parte de #9?

2021-09-29 05:30 UTC, JJ commented on docs/Objetivo-1/ISSUES.md
> +[[HU9](https://github.com/jesusmarzor/Proyecto-IV/issues/11)] &#8594; Como gestor, quiero predecir cuántos son los ingresos obtenidos en el negocio semanalmente.
Y esto ya me parece redundante, la verdad. Pero si hay algún aspecto que me haya perdido, acláralo en la HU.

2021-09-29 05:31 UTC, JJ approved these changes

2021-09-29 09:32 UTC, jesusmarzor commented on docs/Objetivo-1/ISSUES.md
> +[[HU3](https://github.com/jesusmarzor/Proyecto-IV/issues/13)] &#8594; Como cliente, quiero pagar el coste del servicio a la hora de reservar la cita.
En las HUs del cliente puse todo lo que se imaginaria que tendría la futura aplicación web, tanto botones como las acciones que quiere hacer. Pero si las HUs que son más de UI son irrelevantes para la asignatura, ahora las elimino :+1: .

2021-09-29 09:38 UTC, jesusmarzor commented on docs/Objetivo-1/ISSUES.md
> +[[HU4](https://github.com/jesusmarzor/Proyecto-IV/issues/5)] &#8594; Como cliente, quiero tener a mano una forma de contacto con la empresa(email,teléfono,formulario) por si tengo algún problema.
En las HUs del cliente puse todo lo que se imaginaria que tendría la futura aplicación web, tanto botones como las acciones que quiere hacer. Pero si las HUs que son más de UI son irrelevantes para la asignatura, ahora las elimino :+1: .

2021-09-29 09:39 UTC, jesusmarzor commented on docs/Objetivo-1/ISSUES.md
> +[[HU5](https://github.com/jesusmarzor/Proyecto-IV/issues/7)] &#8594; Como trabajador, quiero consultar las citas para ir comprobando las citas de los clientes.
Voy a añadir el **dado que...** a todas las HUs

2021-09-29 14:18 UTC, jesusmarzor commented on docs/Objetivo-1/ISSUES.md
> +
En el HU8, que ya he actualizado las HUs y ahora es la HU7, quiero predecir cuántos clientes habrá cada día ya que si son demasiados necesito más trabajadores. Por ejemplo, en mi caso que sería para la peluquería de mi madre, si cree que el sábado vendrán muchos clientes, llamará a un trabajador para que los clientes no esperen mucha cola(aunque las citas sean cada media hora, puede ser que algún cliente quiera un tinte y este dure más de media hora) ni estén todos dentro del local por tema "covid-19". Se agilizaría el trabajo y los clientes estarían más agradecidos.

2021-09-29 14:20 UTC, jesusmarzor commented
He realizado cambios en mi proyecto con respecto a los comentarios dichos anteriormente :laughing: .

2021-09-29 15:14 UTC, merged